# Generated by Django 5.1.1 on 2024-10-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_cats_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cats',
            name='name',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
